const permissions = require("../config/permissions");

module.exports = [
  {
    name: "HYPEBOTX",
    color: 0xf1c40f,
    hoist: true,
    mentionable: false,
    permissions: [],
  },
  {
    name: "OWNER",
    color: 0xe74c3c,
    hoist: true,
    mentionable: false,
    permissions: permissions.ownerRolePermissions,
  },
  {
    name: "MANAGER",
    color: 0xd35400,
    hoist: true,
    mentionable: false,
    permissions: permissions.adminRolePermissions,
  },
  {
    name: "ADMIN",
    color: 0x2f80ed,
    hoist: true,
    mentionable: true,
    permissions: permissions.adminRolePermissions,
  },
  {
    name: "STAFF",
    color: 0x27ae60,
    hoist: true,
    mentionable: true,
    permissions: permissions.staffRolePermissions,
  },
  {
    name: "IT DEVELOPER",
    color: 0x1abc9c,
    hoist: false,
    mentionable: true,
    permissions: permissions.staffRolePermissions,
  },
  {
    name: "CABIN CREW",
    color: 0x16a085,
    hoist: false,
    mentionable: true,
    permissions: [],
  },
  { name: "GAME BOOSTER", color: 0x1f8b4c, hoist: false, mentionable: true, permissions: [] },
  { name: "SULTAN", color: 0xf1c40f, hoist: true, mentionable: true, permissions: [] },
  { name: "SULTAN HYPERINDO", color: 0xf1c40f, hoist: true, mentionable: true, permissions: [] },
  { name: "VIP CUSTOMER", color: 0x9b59b6, hoist: false, mentionable: true, permissions: [] },
  { name: "DJ", color: 0xe67e22, hoist: false, mentionable: true, permissions: [] },
  { name: "MUTED", color: 0x7f8c8d, hoist: false, mentionable: false, permissions: [] },
  { name: "UNVERIFIED", color: 0x95a5a6, hoist: false, mentionable: false, permissions: [] },
  { name: "MEMBER", color: 0x2ecc71, hoist: true, mentionable: false, permissions: [] },
  { name: "ENHANCED", color: 0x5865f2, hoist: false, mentionable: true, permissions: [] },
  { name: "LEGACY", color: 0x8e44ad, hoist: false, mentionable: true, permissions: [] },
  { name: "PROMO PING", color: 0xf39c12, hoist: false, mentionable: true, permissions: [] },
  { name: "EVENT PING", color: 0xf1c40f, hoist: false, mentionable: true, permissions: [] },
  { name: "SERVER BOOSTER", color: 0xffff00, hoist: false, mentionable: true, permissions: [] },
  { name: "HyperIndo Bot-web", color: 0x95a5a6, hoist: false, mentionable: false, permissions: [] },
  { name: "BOOSTING PING", color: 0xffff00, hoist: false, mentionable: true, permissions: [] },
];
