module.exports = {
  owner: "OWNER",
  hypebotx: "HYPEBOTX",
  coOwner: "CO-OWNER",
  manager: "MANAGER",
  admin: "ADMIN",
  staff: "STAFF",
  pilot: "PILOT",
  member: "MEMBER",
  unverified: "UNVERIFIED",
  customer: "MEMBER",
  // Live server mapping
  vipCustomer: "SULTAN",
  sultanHyperindo: "SULTAN",
  sultan: "SULTAN",
  promoPing: "PROMO PING",
  eventPing: "EVENT PING",
  streamPing: "STREAM PING",
  gtaPing: "GTA PING",
  topupPing: "TOP UP PING",
  jokiPing: "GAME BOOSTER",
  enhanced: "ENHANCED",
  legacy: "LEGACY",
  serverBooster: "SERVER BOOSTER",
  dj: "DJ",
  pramugara: "CABIN CREW",
  // Backward compatibility: some guards/tests still reference `roles.joki`.
  joki: "GAME BOOSTER",
  gameBooster: "GAME BOOSTER",
  penjoki: "GAME BOOSTER",
  itDev: "IT DEVELOPER",
  muted: "MUTED",
  botWeb: "HyperIndo Bot-web",
  selfRoles: ["LEGACY", "ENHANCED"],
};
